### ISSUE TITLE
Incorrect crop rect on Android

### ISSUE THREAD

**Issue by sebazh** [barrsan/react-native-simple-image-cropper#1]
Hello. Thank you for this awesome package, but it seems it doesn't work correctly on Android. It crops only half of width and height. Could you point me what might be wrong please?

Thanks

**Comment by sebazh** [comment]
I didn't find exact reason why, but if i multiply srcSize.w and srcSize.h on 2 before cropping - it crops correctly.

Device: OnePlus One

**Comment by barrsan** [comment]
Hello @sebazh ! Thanks for the feedback!
Can you give a link to the image, which you are trying to crop or link to the snack? I'll try to reproduce your case.

**Comment by barrsan** [comment]
Hi @sebazh! I made changes to the component and crop method. If the problem persists, let me know, I will reopen issue.
