### ISSUE TITLE
Two finger pan?

### ISSUE THREAD

**Issue by barrylachapelle** [barrsan/react-native-simple-image-cropper#12]
Hey there. Thanks for your work on this. It’s exactly what I needed. 

Have you considered allowing for two finger panning? Currently you need to release one finger to go between zoom and pan which doesn’t feel 100% native.

**Comment by barrsan** [comment]
Hey, @barrylachapelle! Thanks for feedback!

To implement this functionality, a third-party [react-native-image-zoom](https://github.com/ascoders/react-native-image-zoom) component is used. It is planned in the future to create its own implementation of this component, but so far, unfortunately, there is not enough free time.

**Comment by barrylachapelle** [comment]
Cool - you can resolve this ;) If you do look at adding multitouch to your package - I hacked it together quite easily using react-native-gesture-handler. Heres an example of nesting gestures...

https://github.com/software-mansion/react-native-gesture-handler/blob/master/Example/scaleAndRotate/index.js

Thanks.

**Comment by barrsan** [comment]
Hey, @barrylachapelle! Sorry for the late reply. I followed your advice and release version 3 with custom image view based on react-native-gesture-handler and react-native-reanimated.

**Comment by barrsan** [comment]
I am closing this issue. If there are comments, you can reopen this issue.
