### ISSUE TITLE
Value from that return ImageCropper.crop is useless

### ISSUE THREAD

**Issue by valin0k** [barrsan/react-native-simple-image-cropper#15]
Hey, how to use value after `ImageCropper.crop`? I got something like this ` file:///data/user/0/com/cache/ReactNative_cropped_image_1510040711431897318.png`. I tried to convert it into blob (new Blob(result, 'name.png')) or file but got error `err TypeError: parts.map is not a function`. And there is no props to specify which type of data should return crop func

**Comment by barrsan** [comment]
Hey! The result of the `ImageCropper.crop` function is the result of `ImageEditor.cropImage` (https://github.com/barrsan/react-native-simple-image-cropper/blob/master/src/ImageCropper.js#L101).
Information about `ImageEditor.cropImage` can be found here: https://github.com/react-native-community/react-native-image-editor#crop-image

**Comment by valin0k** [comment]
@barrsan thank you so much!
