### ISSUE TITLE
timing function not found

### ISSUE THREAD

**Issue by ashwanimm** [barrsan/react-native-simple-image-cropper#33]
My Package.json is:

{
  "name": "crop",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/image-editor": "^2.3.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-redash": "^15.11.1",
    "react-native-simple-image-cropper": "^3.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/runtime": "7.12.1",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

ImageViewer.js at line 99 calls react_native_redash_1.timing function, but this function is not available in react-native-dash. This is the error I am getting:

 ERROR    TypeError: react_native_redash_1.timing is not a function. (In 'react_native_redash_1.timing(__assign({
            from: _this.scale,
            to: minScale
          }, timingDefaultParams))', 'react_native_redash_1.timing' is undefined)

This error is located at:
    in ImageViewer (created by ImageCropper)
    in ImageCropper (at App.js:61)
    in RCTView (at View.js:34)
    in View (at App.js:60)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by gomes042** [comment]
Same issue here.

**Comment by gomes042** [comment]
It seems to be an error with [react-native-redash](https://github.com/wcandillon/react-native-redash) itself.

https://github.com/barrsan/react-native-simple-image-cropper/blob/53bb5c1144d31df45e374cdbadd687901d2ff66a/src/ImageViewer.tsx#L10

I tried with
`import { timing } from 'react-native-redash/src/v1';` but i still got [errors](https://github.com/wcandillon/react-native-redash/issues/366). 

The easiest solution at the moment is to do an older installation of react-native-redash but I still don't know which version is compatible without throw errors.

**Comment by 3GOMESz** [comment]
Well, I fixed the problem but it looks like this project is abandoned...
