### ISSUE TITLE
Unable to Crop Image According to Screen Size

### ISSUE THREAD

**Issue by ammarahm-ed** [barrsan/react-native-simple-image-cropper#4]
Hello there, 
                   Earlier I was trying to implement react-native-image-cropper library in my app but I was facing a problem with some images not loading so I switched to your library. Now I am facing a new problem and I hope you would understand it.

I want to crop the part of Image that is displayed on the phone screen.
![Screenshot_20190825-144619](https://user-images.githubusercontent.com/40239442/63648297-32c6b700-c747-11e9-8ac9-99cff3c324e6.png)
but I am only able to crop only a small part when I zoom in and fill the whole sceen.

![Screenshot_20190825-144910](https://user-images.githubusercontent.com/40239442/63648316-aff22c00-c747-11e9-9860-43ff7fa1657b.png)
`<ImageZoom
        ref={this.imageZoom}
        {...restProps}
        cropWidth={w}
        cropHeight={h}
        imageWidth={w}
        imageHeight={h}
        minScale={minScale}
        onMove={this.handleMove}
        style={{backgroundColor:"white"}} 
      >
        <Image style={{width:w,height:h}} source={imageSrc}  resizeMethod="scale" resizeMode="cover"/>
      </ImageZoom>`

I am able to get the part of image in the screen by making the above changes in your code but doing this does not let me move left or right as the image has been resized automatically when I set `resizeMode="cover"`. 

I want that when I open an image, it fills the whole screen and I can drag it left and right and crop the part that is showing in the screen. I hope you understand the issue. Thank you for making this great library.

**Comment by barrsan** [comment]
Hi, @thewisefarmerr! Thanks for feedback!

Initially, this component was planned to be used for cropping square avatars. I wanted to achieve something like cropping an avatar on Instagram.
![photo_2019-08-26](https://user-images.githubusercontent.com/11488110/63717474-61cd4d80-c859-11e9-99ae-4960357350b5.jpeg)

I made changes to the component. Now it can be used not only for getting square images.

Do you need something like that?
**DEMO** - https://snack.expo.io/@barrsan/react-native-simple-image-cropper-demo-v1.1.2

**Comment by ammarahm-ed** [comment]
Yes definitely, I am glad that you have fixed it in such short period of time. Actually I in the past days I was able to get the functionality I wanted with react-native-image-cropper however it is not very performant on low end devices because it uses gl-react and gl-react-native that put quite some load on the system. This library is a drop in replacement for it. Thank  you very much again! I will test and and report back if I find any other problem! Happy coding!

**Comment by barrsan** [comment]
Thanks! I'm glad that the last changes have solved your problem. I close this issue.
