### ISSUE TITLE
unable crop images from camera

### ISSUE THREAD

**Issue by vbashiri** [barrsan/react-native-simple-image-cropper#5]
Hi,
When I import images from Gallery, it works perfectly, but when I take picture from camera, I can view the image and zoom/move but when crop the image, catches this error:

Requested column: 0, # of columns: 0

**Comment by barrsan** [comment]
Hi, @vbashiri! May be this info help you. A similar error is considered here https://github.com/dgladkov/react-native-image-rotate/issues/10.

**Comment by vbashiri** [comment]
Thank you sir,
It fixed my issue.
