### ISSUE TITLE
Getting error for ImageEditor (has been removed from React Native)

### ISSUE THREAD

**Issue by sahilvicesoftware** [barrsan/react-native-simple-image-cropper#6]
Use 'react-native-image-editor'

**Comment by barrsan** [comment]
Hi @sahilvicesoftware! I updated the version of this library. Now using [@react-native-community/image-editor](https://github.com/react-native-community/react-native-image-editor). Please check out [README](https://github.com/barrsan/react-native-simple-image-cropper#installation). In short, you will also have to install [@react-native-community/image-editor](https://github.com/react-native-community/react-native-image-editor)

**Comment by sahilvicesoftware** [comment]
> Hi @sahilvicesoftware! I updated the version of this library. Now using [@react-native-community/image-editor](https://github.com/react-native-community/react-native-image-editor). Please check out [README](https://github.com/barrsan/react-native-simple-image-cropper#installation). In short, you will also have to install [@react-native-community/image-editor](https://github.com/react-native-community/react-native-image-editor)

Thanks @barrsan
