### ISSUE TITLE
Composant does not update

### ISSUE THREAD

**Issue by batical** [barrsan/react-native-simple-image-cropper#7]
Hello,

first thanks for you package, saves me some times.

I had a small issue the way I used it. I have a grid of picture and display the selected one in the component.

For the default image loaded, cropping is working fine but when I changed, it is not working correctly

The function inside your componentDidMount  need to be done when imageUri props changed.
For a quick test, I also did it in componentDidUpate while checking if the props imageUri is different

hope this help

**Comment by barrsan** [comment]
Hi, @batical! Thanks for feedback! Great idea! I added the implementation of your idea to version 2.0.2. Thanks for the advice. If you still have ideas for improvement - feel free to create a PR.
