### ISSUE TITLE
Is it possible to crop a image with its full width?

### ISSUE THREAD

**Issue by alvazzlau** [barrsan/react-native-simple-image-cropper#8]
I have a image with {width: 500, height: 1000}. i want to crop the image to like {width: 500, height: 500}.
But my device's width is only 420, then i can't get the full width of the image as my device can not show the full image.

**Comment by alvazzlau** [comment]
nvm, i just found the problem

**Comment by barrsan** [comment]
Hi @alvazzlau! Glad you found a solution to the problem. If you have time, can you describe a solution to the problem here? Maybe it will be useful to someone. Thank!

**Comment by hhunaid** [comment]
Is it possible to do this?
