### ISSUE TITLE
Support for RN 0.61.4?

### ISSUE THREAD

**Issue by leonsoh** [barrsan/react-native-simple-image-cropper#9]
Hello, thank you for this library. 👍

Previously when I was using RN 0.60~ it was working fine. It was when I updated to RN 0.61.4 recently and had an issue.

I had encountered a warning when the **image was cropped**:
```
Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. 
Please update to themoduleForClass API or turboModuleLookupDelegate API.
```

I understand that this library is using `react-native-image-editor` and I am unsure which one is causing the warnings.

I am using React Native **0.61.4** on iPhone 11 **iOS 13.2.2** simulator.

<img width="415" alt="image-cropper-warnings" src="https://user-images.githubusercontent.com/27716791/69299768-56b56e00-0c4c-11ea-9444-0b8c43c3aad4.png">

**Comment by leonsoh** [comment]
Further troubleshooting on **Android**,
``` Error [TypeError: null is not an object (evaluating 'RNCImageEditor.cropImage')]```

**Comment by barrsan** [comment]
Hello @leonsoh! Thanks for feedback! Sorry for late answer. 🙏 Yes, the library uses `react-native-image-editor`. The reason for the yellow screen to appear is in the `react-native-image-editor` library.

A warning is shown as a result of code running on this line: https://github.com/react-native-community/react-native-image-editor/blob/master/ios/RNCImageEditor.m#L56

A warning is generated here: https://github.com/facebook/react-native/blob/0.61-stable/React/CoreModules/RCTImageLoader.mm#L962

Temporary solution - turn off a yellow screen: https://github.com/barrsan/react-native-simple-image-cropper/blob/master/example/index.js#L9

I updated the version of RN in the example app to 0.61.4 - it works like with RN 0.61.2: https://github.com/barrsan/react-native-simple-image-cropper/blob/master/example/package.json#L15

**Comment by leonsoh** [comment]
@barrsan  Thanks for the response.  Sorry but I had another question not sure is it related so I will not open another issue for now.

This issue is regarding`[TypeError: null is not an object (evaluating 'RNCImageEditor.cropImage')]`

I am able to get the cropped image file uri but was unable to proceed on to the next step.
(It will not log out `results`)

Example code: 
```
ImageCropper.crop({
        ...cropCoverParams,
        imageUri: profilePicture.uri,
        cropSize,
        cropAreaSize,
      }),
    ]).then((results) => {
      console.log('Success', results);
}
```
This happened on **Android** only
React Native: `0.61.4`
Device: Emulator, Pixel API 29

**Comment by barrsan** [comment]
I can’t say exactly what the problem is, but something seems to be wrong with the `react-native-image-editor` library link in you app.

I checked today an example app in android emulator - it works correctly. Please, see example app: https://github.com/barrsan/react-native-simple-image-cropper/tree/master/example

Issue about the error https://github.com/react-native-community/react-native-image-editor/issues/38

**Comment by leonsoh** [comment]
Thanks, I actually had to manually link `react-native-image-editor` for Android and it will solve the error.
